name: Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: team18-be-jar
          path: build/libs/team18-be-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR file
        uses: actions/download-artifact@v2
        with:
          name: team18-be-jar

      - name: Deploy to GCP
        run: |
          # 필요한 패키지 설치
          sudo apt-get install -y google-cloud-sdk

          # GCP 인증
          echo "${{ secrets.HIREHIGHER_GCP_SSH_KEY }}" > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json

          # GCP VM 인스턴스에 JAR 파일 전송
          gcloud compute scp ./build/libs/team18-be-0.0.1-SNAPSHOT.jar hirehigher-api:/home/hirehigher/repository --zone asia-northeast3-a

          # GCP VM에서 배포 쉘 스크립트 실행
          gcloud compute ssh hirehigher-api --zone asia-northeast3-a --command 'bash /home/hirehigher/repository/deploy.sh'
