name: Deploy to GCP

on:
  push:
    branches:
      - Master
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Configure Production Properties
        run: |
          touch ./src/main/resources/application-prod.properties
          echo "${{ secrets.APPLICATION_PROD_PROPERTIES }}" > ./src/main/resources/application-prod.properties

      - name: Configure GCS Properties
        run: |
          touch ./src/main/resources/application-gcs.properties
          echo "${{ secrets.APPLICATION_GCS_PROPERTIES }}" > ./src/main/resources/application-gcs.properties

      - name: Configure Test Properties
        run: |
          touch ./src/main/resources/application-test.properties
          echo "${{ secrets.APPLICATION_TEST_PROPERTIES }}" > ./src/main/resources/application-test.properties

      - name: gradlew에 실행 권한 부여
        run: chmod +x ./gradlew
      
      - name: 배포 파일 생성
        run: ./gradlew bootJar

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: team18-be-jar
          path: build/libs/team18-be-0.0.1-SNAPSHOT.jar
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR file
        uses: actions/download-artifact@v3
        with:
          name: team18-be-jar

      - name: Configure SSH private key
        run: |
          touch ./key-hirehigher
          echo "${{ secrets.HIREHIGHER_GCP_SSH_KEY }}" > ./key-hirehigher
          chmod 600 ./key-hirehigher

      - name: Add GCP VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.GCP_VM_IP }}" >> ~/.ssh/known_hosts

      - name: Deploy to GCP
        run: |
          # scp로 VM에 jar 파일 전송
          scp -o StrictHostKeyChecking=no -i ./key-hirehigher ./build/libs/team18-be-0.0.1-SNAPSHOT.jar hirehigher@${{ secrets.GCP_VM_IP }}:/home/hirehigher/repository
