name: Deploy to GCP

on:
  push:
    branches:
      - Master
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Configure Production Properties
        run: |
          touch ./src/main/resources/application-prod.properties
          echo "${{ secrets.APPLICATION_PROD_PROPERTIES }}" > ./src/main/resources/application-prod.properties

      - name: Configure GCS Properties
        run: |
          touch ./src/main/resources/application-gcs.properties
          echo "${{ secrets.APPLICATION_GCS_PROPERTIES }}" > ./src/main/resources/application-gcs.properties

      - name: Configure Test Properties
        run: |
          touch ./src/main/resources/application-test.properties
          echo "${{ secrets.APPLICATION_TEST_PROPERTIES }}" > ./src/main/resources/application-test.properties

      - name: gradlew에 실행 권한 부여
        run: chmod +x ./gradlew
      
      - name: 배포 파일 생성
        run: ./gradlew bootJar

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: team18-be-jar
          path: build/libs/team18-be-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR file
        uses: actions/download-artifact@v3
        with:
          name: team18-be-jar

      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.HIREHIGHER_GCP_KEY }}

      - name: Deploy to GCP
        run: |
          gcloud compute scp /home/runner/work/Team18_BE/Team18_BE/team18-be-0.0.1-SNAPSHOT.jar hirehigher-api:/home/hirehigher/repository
          
          gcloud compute ssh --project=${{ secrets.GCP_PROJECT_ID }} --zone=${{ secrets.GCP_ZONE }} ${{ secrets.GCP_VM_USER_NAME }}@${{ secrets.GCP_VM_INSTANCE_NAME }} -- \
          "cd /home/hirehigher/repository && \
          ./deploy.sh"
        
